# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Company.create([
	{ name: 'Company Information Not Available' },
	{ name: 'Motorola Solutions', website_url: 'http://www.motorolasolutions.com/' },
	{ name: 'Vertex Standard', website_url: 'http://www.vertexstandard.com/' },
	{ name: 'Emergency CallWorks', website_url: 'https://www.emergencycallworks.com/' },
	{ name: 'Zebra Technologies', website_url: 'https://www.zebra.com/' },
	{ name: 'Motorola Mobility', website_url: 'http://www.motorola.com/' },
	{ name: 'Cambium Networks', website_url: 'http://www.cambiumnetworks.com/' },
	{ name: 'NICE Systems', website_url: 'http://www.nice.com/' },
	{ name: 'Airbus DS Communications', website_url: 'http://www.airbus-dscomm.com/' },
	{ name: 'ASTRON Corporation', website_url: 'http://www.astroncorp.com/' },
	{ name: 'Avaya', website_url: 'http://www.avaya.com/' },
	{ name: 'CommScope', website_url: 'http://www.commscope.com/' },
	{ name: 'AVTEC', website_url: 'http://www.avtecinc.com/' },
	{ name: 'GAI-Tronics', website_url: 'https://www.gai-tronics.com/' },
	{ name: 'VMware', website_url: 'http://www.vmware.com/' },
	{ name: 'Giant International', website_url: 'https://shop.giantintl.com/' },
	{ name: 'Cellstar' },
	{ name: 'Locus Diagnostics', website_url: 'http://www.locususa.com/' },
	{ name: 'Futurecom', website_url: 'http://www.futurecom.com/' },
	{ name: 'EMR Corp', website_url: 'http://www.emrcorp.com/' },
	{ name: 'Arden Design Center (ADC)' }
])

Product.create([
	{ company_id: 2, name: 'Si300', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/body-worn-cameras/si300/Si300-Body-Camera.jpg#1' },
	{ company_id: 2, name: 'Si500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/body-worn-cameras/Si500/Si500_Front_324x324.jpg#3' },
	{ company_id: 2, name: 'LEX L10', image_url: 'http://www.motorolasolutions.com/content/dam/msi/docs/products/lte-user-devices/product-lex-755-bart-lipinski0551_w_megaLEX_Activity_6.jpg#1' },
	{ company_id: 2, name: 'VML 750', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/public_safety_lte/vml750/_images/vml750_front_angle_lg.jpg' },
	{ company_id: 2, name: 'CRYPTR 2', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios_-_public_safety/encryption/ame1000/cryptr_micro_encryption_unit/_images/cryptr-micro-web-324x324.jpg' },
	{ company_id: 2, name: 'CRYPTR micro', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios_-_public_safety/encryption/ame1000/cryptr_micro_encryption_unit/_images/cryptr-micro-web-324x324.jpg' },
	{ company_id: 2, name: 'VML700', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/public_safety_lte/vml700/_images/static_files/vml700_lg-us-en.jpg' },
	{ company_id: 2, name: 'UM1000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/public_safety_lte/_images/um1000-angle-transp-324x324.jpg#2' },
	{ company_id: 2, name: 'MW810', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/mobile_computers/vehicle-mounted_computers/mw810/_images/static_files/primary-mw810-3up-white-324x324.jpg#1' },
	{ company_id: 2, name: 'ADVISOR II', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/pagers/advisor_ii/_images/static_files/b2b_advisor_ii_lg_us-en.jpg' },
	{ company_id: 2, name: 'MINITOR VI', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/pagers/minitor_vi/_images/staticfiles/minitor_vi_front_lg.jpg' },
	{ company_id: 2, name: 'APX 8000XE', image_url: '' },
	{ company_id: 2, name: 'APX 8000', image_url: '' },
	{ company_id: 2, name: 'APX 7000', image_url: '' },
	{ company_id: 2, name: 'APX 6000', image_url: '' },
	{ company_id: 2, name: 'APX 4000', image_url: '' },
	{ company_id: 2, name: 'APX 7000XE', image_url: '' },
	{ company_id: 2, name: 'APX 6000XE', image_url: '' },
	{ company_id: 2, name: 'APX 7000L', image_url: '' },
	{ company_id: 2, name: 'APX 3000', image_url: '' },
	{ company_id: 2, name: 'APX 1000', image_url: '' },
	{ company_id: 2, name: 'SRX 2200', image_url: '' },
	{ company_id: 2, name: 'APX 4000XH', image_url: '' },
	{ company_id: 2, name: 'APX 6500', image_url: '' },
	{ company_id: 2, name: 'APX Mobile Siren and Light Interface Module', image_url: '' },
	{ company_id: 2, name: 'APX Dual Radio', image_url: '' },
	{ company_id: 2, name: 'APX 4500', image_url: '' },
	{ company_id: 2, name: 'APX 7500', image_url: '' },
	{ company_id: 2, name: 'Digital Vehicular Repeater System (DVRS)', image_url: '' },
	{ company_id: 2, name: 'APX 1500', image_url: '' },
	{ company_id: 2, name: 'VRX1000', image_url: '' },
	{ company_id: 2, name: 'ASTRO SPECTRA Locomotive', image_url: '' },
	{ company_id: 2, name: 'ASTRO SPECTRA Motorcycle', image_url: '' },
	{ company_id: 2, name: 'ASTRO SPECTRA Plus', image_url: '' },
	{ company_id: 2, name: 'SPECTRA', image_url: '' },
	{ company_id: 2, name: 'Saber I R', image_url: '' },
	{ company_id: 2, name: 'Saber II R', image_url: '' },
	{ company_id: 2, name: 'Saber', image_url: '' },
	{ company_id: 2, name: 'XTS 5000', image_url: '' },
	{ company_id: 2, name: 'XTS 3500', image_url: '' },
	{ company_id: 2, name: 'XTS 2500', image_url: '' },
	{ company_id: 2, name: 'XTS 1500', image_url: '' },
	{ company_id: 2, name: 'ASTRO XTL 5000', image_url: '' },
	{ company_id: 2, name: 'ASTRO 25 XTL 2500', image_url: '' },
	{ company_id: 2, name: 'ASTRO XTL 1500', image_url: '' },
	{ company_id: 2, name: 'XPR 5000e', image_url: '' },
	{ company_id: 2, name: 'XPR 5550e', image_url: '' },
	{ company_id: 2, name: 'XPR 5580e', image_url: '' },
	{ company_id: 2, name: 'XPR 5350e', image_url: '' },
	{ company_id: 2, name: 'XPR 5380e', image_url: '' },
	{ company_id: 2, name: 'CM200d', image_url: '' },
	{ company_id: 2, name: 'CM300d', image_url: '' },
	{ company_id: 2, name: 'XPR 5350', image_url: '' },
	{ company_id: 2, name: 'XPR 5380', image_url: '' },
	{ company_id: 2, name: 'XPR 5550', image_url: '' },
	{ company_id: 2, name: 'XPR 5550', image_url: '' },
	{ company_id: 2, name: 'XPR 5580', image_url: '' },
	{ company_id: 2, name: 'XPR 4350', image_url: '' },
	{ company_id: 2, name: 'XPR 4380', image_url: '' },
	{ company_id: 2, name: 'XPR 4550', image_url: '' },
	{ company_id: 2, name: 'XPR 4580', image_url: '' },
	{ company_id: 2, name: 'XPR 2500', image_url: '' },
	{ company_id: 2, name: 'XPR 7550e', image_url: '' },
	{ company_id: 2, name: 'XPR 7580e', image_url: '' },
	{ company_id: 2, name: 'XPR 7350e', image_url: '' },
	{ company_id: 2, name: 'XPR 7380e', image_url: '' },
	{ company_id: 2, name: 'XPR 3500e', image_url: '' },
	{ company_id: 2, name: 'XPR 3300e', image_url: '' },
	{ company_id: 2, name: 'SL 7550e', image_url: '' },
	{ company_id: 2, name: 'SL 7580e', image_url: '' },
	{ company_id: 2, name: 'SL 7590e', image_url: '' },
	{ company_id: 2, name: 'CP200d', image_url: '' },
	{ company_id: 2, name: 'SL 7550', image_url: '' },
	{ company_id: 2, name: 'SL 7580', image_url: '' },
	{ company_id: 2, name: 'SL 7590', image_url: '' },
	{ company_id: 2, name: 'SL 300 Active View Display', image_url: '' },
	{ company_id: 2, name: 'SL 300 Non-Display', image_url: '' },
	{ company_id: 2, name: 'XPR 6580 IS', image_url: '' },
	{ company_id: 2, name: 'XPR 7550', image_url: '' },
	{ company_id: 2, name: 'XPR 7350', image_url: '' },
	{ company_id: 2, name: 'XPR 7580', image_url: '' },
	{ company_id: 2, name: 'XPR 7380', image_url: '' },
	{ company_id: 2, name: 'XPR 6100', image_url: '' },
	{ company_id: 2, name: 'XPR 6350', image_url: '' },
	{ company_id: 2, name: 'XPR 6380', image_url: '' },
	{ company_id: 2, name: 'XPR 6550', image_url: '' },
	{ company_id: 2, name: 'XPR 6580', image_url: '' },
	{ company_id: 2, name: 'XPR 3300', image_url: '' },
	{ company_id: 2, name: 'XPR 3500', image_url: '' },
	{ company_id: 2, name: 'XPR 7550 IS', image_url: '' },
	{ company_id: 2, name: 'XPR 6300', image_url: '' },
	{ company_id: 2, name: 'XPR 6500', image_url: '' },
	{ company_id: 2, name: 'CLP1010', image_url: '' },
	{ company_id: 2, name: 'CLP1040', image_url: '' },
	{ company_id: 2, name: 'CLP1060', image_url: '' },
	{ company_id: 2, name: 'CLS1110', image_url: '' },
	{ company_id: 2, name: 'CLS1410', image_url: '' },
	{ company_id: 2, name: 'DLR1020', image_url: '' },
	{ company_id: 2, name: 'DLR1060', image_url: '' },
	{ company_id: 2, name: 'DTR410', image_url: '' },
	{ company_id: 2, name: 'DTR550', image_url: '' },
	{ company_id: 2, name: 'RDU4100', image_url: '' },
	{ company_id: 2, name: 'RDU4160D', image_url: '' },
	{ company_id: 2, name: 'RDV5100', image_url: '' },
	{ company_id: 2, name: 'RMU2040', image_url: '' },
	{ company_id: 2, name: 'RMU2043', image_url: '' },
	{ company_id: 2, name: 'RMM2050', image_url: '' },
	{ company_id: 2, name: 'RMU2080', image_url: '' },
	{ company_id: 2, name: 'RMU2080D', image_url: '' },
	{ company_id: 2, name: 'RMV2080', image_url: '' },
	{ company_id: 2, name: 'RDU2020', image_url: '' },
	{ company_id: 2, name: 'RDU2080D', image_url: '' },
	{ company_id: 2, name: 'RDV2020', image_url: '' },
	{ company_id: 2, name: 'RDV2080D', image_url: '' },
	{ company_id: 2, name: 'CDM1550 LS+', image_url: '' },
	{ company_id: 2, name: 'CDM1250', image_url: '' },
	{ company_id: 2, name: 'CM200', image_url: '' },
	{ company_id: 2, name: 'CDM1550', image_url: '' },
	{ company_id: 2, name: 'CDM750', image_url: '' },
	{ company_id: 2, name: 'PM1200', image_url: '' },
	{ company_id: 2, name: 'CM300', image_url: '' },
	{ company_id: 2, name: 'PM1500', image_url: '' },
	{ company_id: 2, name: 'PM400', image_url: '' },
	{ company_id: 2, name: 'Mag One BPR40', image_url: '' },
	{ company_id: 2, name: 'Mag One BPR20', image_url: '' },
	{ company_id: 2, name: 'CP110 Display', image_url: '' },
	{ company_id: 2, name: 'CP110 Non-Display', image_url: '' },
	{ company_id: 2, name: 'CP185', image_url: '' },
	{ company_id: 2, name: 'CP200', image_url: '' },
	{ company_id: 2, name: 'DTR650', image_url: '' },
	{ company_id: 2, name: 'EX500', image_url: '' },
	{ company_id: 2, name: 'EX600-XLS', image_url: '' },
	{ company_id: 2, name: 'EX560-XLS', image_url: '' },
	{ company_id: 2, name: 'HT1250', image_url: '' },
	{ company_id: 2, name: 'MT 1500', image_url: '' },
	{ company_id: 2, name: 'HT750', image_url: '' },
	{ company_id: 2, name: 'HT1250 LS+', image_url: '' },
	{ company_id: 2, name: 'PR1500', image_url: '' },
	{ company_id: 2, name: 'PR400', image_url: '' },
	{ company_id: 2, name: 'PR860', image_url: '' },
	{ company_id: 2, name: 'VL50', image_url: '' },
	{ company_id: 2, name: 'AXV5100', image_url: '' },
	{ company_id: 2, name: 'CP125', image_url: '' },
	{ company_id: 2, name: 'CP100', image_url: '' },
	{ company_id: 2, name: 'CP150', image_url: '' },
	{ company_id: 2, name: 'EX600', image_url: '' },
	{ company_id: 2, name: 'HT1250 LS', image_url: '' },
	{ company_id: 2, name: 'HT1250-XLS', image_url: '' },
	{ company_id: 2, name: 'MTX8250', image_url: '' },
	{ company_id: 2, name: 'MTX-LS', image_url: '' },
	{ company_id: 2, name: 'MTX8250-LS', image_url: '' },
	{ company_id: 2, name: 'MTX850', image_url: '' },
	{ company_id: 2, name: 'MTX850-LS', image_url: '' },
	{ company_id: 2, name: 'MTX9000', image_url: '' },
	{ company_id: 2, name: 'MTX9250', image_url: '' },
	{ company_id: 2, name: 'MTX950', image_url: '' },
	{ company_id: 2, name: 'VISAR', image_url: '' },
	{ company_id: 2, name: 'XU1100', image_url: '' },
	{ company_id: 2, name: 'VL130', image_url: '' },
	{ company_id: 2, name: 'XU2100', image_url: '' },
	{ company_id: 2, name: 'XV2100', image_url: '' },
	{ company_id: 2, name: 'XV1100', image_url: '' },
	{ company_id: 2, name: 'Talkabout T605 H20', image_url: '' },
	{ company_id: 2, name: 'Talkabout T600 H2O', image_url: '' },
	{ company_id: 2, name: 'Talkabout T480', image_url: '' },
	{ company_id: 2, name: 'Talkabout T465', image_url: '' },
	{ company_id: 2, name: 'Talkabout T460', image_url: '' },
	{ company_id: 2, name: 'Talkabout T400', image_url: '' },
	{ company_id: 2, name: 'Talkabout T260', image_url: '' },
	{ company_id: 2, name: 'Talkabout T200', image_url: '' },
	{ company_id: 2, name: 'Talkabout T107', image_url: '' },
	{ company_id: 2, name: 'Talkabout T100', image_url: '' },
	{ company_id: 2, name: 'Talkabout MU350R', image_url: '' },
	{ company_id: 2, name: 'Talkabout MU354R', image_url: '' },
	{ company_id: 2, name: 'Talkabout MS355R', image_url: '' },
	{ company_id: 2, name: 'MS350R Talkabout Two-Way Radio', image_url: '' },
	{ company_id: 2, name: 'Talkabout MT352TPR', image_url: '' },
	{ company_id: 2, name: 'MT350R Two-Way Radio', image_url: '' },
	{ company_id: 2, name: 'Talkabout MT352R', image_url: '' },
	{ company_id: 2, name: 'Talkabout MR355R', image_url: '' },
	{ company_id: 2, name: 'Talkabout MR350TPR', image_url: '' },
	{ company_id: 2, name: 'MR350R Talkabout Two-Way Radio', image_url: '' },
	{ company_id: 2, name: 'Talkabout MJ270R', image_url: '' },
	{ company_id: 2, name: 'Talkabout MH230TPR', image_url: '' },
	{ company_id: 2, name: 'MH230R Talkabout Two-Way Radio', image_url: '' },
	{ company_id: 2, name: 'Talkabout MD207R', image_url: '' },
	{ company_id: 2, name: 'Talkabout MD200TPR', image_url: '' },
	{ company_id: 2, name: 'Talkabout MD200R', image_url: '' },
	{ company_id: 2, name: 'Talkabout MG160A', image_url: '' },
	{ company_id: 2, name: 'Talkabout MG167A', image_url: '' },
	{ company_id: 2, name: 'Talkabout FV300', image_url: '' },
	{ company_id: 2, name: 'Talkabout T9680RSAME', image_url: '' }
])

Technologist.create([
	{ name: 'Technical Support Not Available' },
	{ name: 'SSC APX', internal_phone: 'XGPS-SSC APX', external_phone: '800-422-4210 Options 3 > 3', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'Vertex Standard', internal_phone: 'XGPS-Vertex Tech Support', external_phone: '800-283-7839', hours: 'M-F 7:00a-7:00p CST', escalation: 'Contact Greg Spears (CGS006)' },
	{ name: 'Zebra Technologies', external_phone: '800-653-5350' },
	{ name: 'Cambium Networks', external_phone: '888-863-5250' },
	{ name: 'CCS Business Radio', internal_phone: 'XGPS-CCS RBR Support', hours: 'M-F 8:00a-5:00p CST' },
	{ name: 'CCS Customer Service', internal_phone: 'XGPS-CCS Dealer Support', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'CCS Learning Management System (LMS)', internal_phone: 'XGPS-CCS LMS', hours: 'M-F 7:00a-6:00p CST' },
	{ name: 'CCS Motorola Online (MOL)', internal_phone: 'XGPS-CCS MOL', hours: 'M-F 7:00a-6:00p CST' },
	{ name: 'GAI-Tronics Support', external_phone: '800-492-1212' },
	{ name: 'iDEN Dispatch', internal_phone: 'XGPS-iDEN Dispatch', hours: 'M-F 7:00a-3:00a CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'iDEN iBSC / Harmony / LTE / VPU', internal_phone: 'XGPS-iDEN iBSC', hours: 'M-F 7:30a-10:30p CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'iDEN Melody / Harmony / EBTS', internal_phone: 'XGPS-iDEN Melody', hours: 'M-F 7:30a-10:30p CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'iDEN OMC / Oracle', internal_phone: 'XGPS-iDEN OMC', hours: 'M-F 24x5', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'IDEN Overall / System', internal_phone: 'XGPS-iDEN Overall', hours: 'M-F 9:00a-3:00p CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'iDEN Packet Data', internal_phone: 'XGPS-iDEN Packet', hours: 'M-F 7:00a-3:00a CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'iDEN Switching / MSC', internal_phone: 'XGPS-iDEN Switching', hours: 'M-F 6:00a-3:30a CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'SPSS CAD', internal_phone: 'XGPS-PSA-CAD' },
	{ name: 'SPSS CSR 311', internal_phone: 'XGPS-PSA CSR 311' },
	{ name: 'SPSS Jail Management', internal_phone: 'XGPS-PSA Jail Sys' },
	{ name: 'SPSS LRMS', internal_phone: 'XGPS-PSA LRMS' },
	{ name: 'SPSS Mobile Applications', internal_phone: 'XGPS-PSA Mob Apps' },
	{ name: 'SPSS Salt Lake', internal_phone: 'XGPS-PSA RMS' },
	{ name: 'SSC ASTRO 25', internal_phone: 'XGPS-SSC Astro25', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC ASTRO Consoles', internal_phone: 'XGPS-SSC Console Astro', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC ASTRO Legacy', internal_phone: 'Subscriber - Astro Legacy Subs', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC Console Voice Systems', internal_phone: 'XGPS-SSC Console Voice Systems', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC Data Infrastructure', internal_phone: 'XGPS-SSC Data Infrastructure', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC Dispatch Services', internal_phone: 'XGPS-SSC Dispatch Services', hours: '24x7x365' },
	{ name: 'SSC LTE Handheld', internal_phone: 'XGPS-SSC LTE HANDHELD', hours: 'M-F 7:00a-7:00p CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'SSC LTE TSO', internal_phone: 'XGPS-SSC LTE TSO', hours: 'M-F 6:00a-5:00p CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'SSC LTE Provisioning', internal_phone: 'XGPS-SSC LTE PROV', hours: 'M-F 7:00a-7:00p CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'SSC LTE VSM', internal_phone: 'XGPS-SSC LTE VSM', hours: 'M-F 7:00a-7:00p CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'SSC MC Series Desksets & Paging', internal_phone: 'XGPS-SSC MC Series Deskset', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC MOSCAD', internal_phone: 'XGPS-SSC Data Infrastructure', hours: 'M-F 7:00a-7:00p CST', escalation: '24x7 on-call support for Sev 1 / Sev 2 issues' },
	{ name: 'SSC MOTOTRBO Applications', internal_phone: 'XGPS-SSC TRBO Apps', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC MOTOTRBO Connect Plus', internal_phone: 'XGPS-SSC Connect Plus', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC MOTOTRBO Digital Conventional', internal_phone: 'XGPS-SSC TRBO Digital Conv', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC MOTOTRBO IP Site Connect', internal_phone: 'XGPS-SSC IP Site Connect', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC Network Monitoring Operations (NMO)', internal_phone: 'XGPS-SSC NMO', hours: '24x7x365' },
	{ name: 'SSC PCR Analog', internal_phone: 'XGPS-SSC PCR ANALOG', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC Presales', internal_phone: 'XGPS-SSC Presale', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC SmartNet', internal_phone: 'XGPS-SSC Smartnet', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'SSC XTS / XTL', internal_phone: 'XGPS-SSC XTS/XTL', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'Vertex Standard Online (VSOL)', internal_phone: 'XGPS-Vertex VSOL', hours: 'M-F 7:00a-7:00p CST', escalation: 'Contact Greg Spears (CGS006)' },
	{ name: 'Twisted Pair', external_phone: '206-812-2390', hours: 'M-F 10:00a-8:00p CST' },
	{ name: 'Giant International', external_phone: '800-353-2729', hours: 'M-F 7:00a-7:00p CST' },
	{ name: 'Motorola Mobility', external_phone: '800-331-6456' },
	{ name: 'Advance Tec Industries', external_phone: '866-881-8211' },
	{ name: 'Futurecom', internal_phone: 'See Notes', external_phone: '800-701-9180' },
	{ name: 'Emergency Callworks', external_phone: '855-329-1911' },
	{ name: 'CCS Consumer Radio', internal_phone: 'XGPS-CCS Consumer', hours: 'M-F 8:00a-5:00p CST' }
])

Servicer.create([
	{ name: 'Repair Service Not Available' },
	{ name: 'Motorola Repair Center (MRC) - El Paso', internal_phone: 'XGPS-CCS Radio Repair', address: '1220 Don Haskins Dr, Suite A, El Paso, TX 79936' },
	{ name: 'Motorola Repair Center (MRC) - Elgin', internal_phone: 'XGPS-CCS Radio Repair', address: '2204 Galvin Dr, Elgin, IL 60124' },
	{ name: 'Motorola Federal Technical Center', internal_phone: 'XGPS-CCS Fed Govt', external_phone: '800-969-6680', address: '10105 Senate Dr, Lanham, MD 20706' },
	{ name: 'Motorola Canada Radio Repair Depot', internal_phone: 'XGPS-CCS Canada', external_phone: '800-543-3222', address: '8133 Warden Ave, Markham, Ontario, Canada L6G183' },
	{ name: 'Infrastructure Depot Operations (IDO)', internal_phone: 'XGPS-SSC Return Authorization', address: '2214 Galvin Dr, Elgin, IL 60124' },
	{ name: 'CCS Business Radio', internal_phone: 'XGPS-CCS RBR Support' },
	{ name: 'Vertex Standard Repair Center', external_phone: '800-283-7839', address: '7201-A Intermodal Drive, Louisville KY 40258' },
	{ name: 'Zebra Technologies', external_phone: '800-653-5350' },
	{ name: 'Futurecom', internal_phone: 'See Notes', external_phone: '800-701-9180' },
	{ name: 'AdvanceTec Industries', external_phone: '866-881-8211' },
	{ name: 'Astron Corp', external_phone: '949-458-7277' },
	{ name: 'AvtechTyee', external_phone: '425-290-3100 ' },
	{ name: 'Cadex Electronics', external_phone: '800-565-5228' },
	{ name: 'David Clark Co', external_phone: '508-751-5800' },
	{ name: 'Gamber Johnson', external_phone: '800-456-6868 x301' },
	{ name: 'Giant International', external_phone: '800-353-2729' },
	{ name: 'GAI-Tronics', external_phone: '800-492-1212' },
	{ name: 'Global Data Specialists', external_phone: '800-451-3464' },
	{ name: 'International Radio Repair', internal_phone: 'XGPS-CCS INTL' },
	{ name: 'Microwave Data Systems', external_phone: '585-242-9600' },
	{ name: 'Microwave Network', external_phone: '800-545-0334' },
	{ name: 'Newmar', external_phone: '800-854-3906' },
	{ name: 'Business Radio Repair', internal_phone: 'XGPS-CCS RBR Dealer Support' },
	{ name: 'Telex', external_phone: '800-898-6723' },
	{ name: 'TPL Communications', external_phone: '323-256-3000' },
	{ name: 'Zetron', external_phone: '425-820-6363' },
	{ name: 'Lorain Reltec Network', external_phone: '800-752-8733 x116' },
	{ name: 'Cambium Networks', external_phone: '888-863-5250' },
	{ name: 'CCS Consumer Radio', internal_phone: 'XGPS-CCS Consumer', hours: 'M-F 8:00a-5:00p CST' }
])

TechnologistAssignment.create([
	{ product_id: '1', technologist_id: '2', condition: 'All' },
	{ product_id: '2', technologist_id: '2', condition: 'All' },
	{ product_id: '3', technologist_id: '30', condition: 'All' },
	{ product_id: '4', technologist_id: '30', condition: 'All' },
	{ product_id: '5', technologist_id: '28', condition: 'All' },
	{ product_id: '6', technologist_id: '28', condition: 'All' },
	{ product_id: '7', technologist_id: '30', condition: 'All' },
	{ product_id: '8', technologist_id: '33', condition: 'All' },
	{ product_id: '9', technologist_id: '30', condition: 'All' },
	{ product_id: '10', technologist_id: '34', condition: 'All' },
	{ product_id: '11', technologist_id: '1', condition: 'All' },
	{ product_id: '12', technologist_id: '34', condition: 'All' },
	{ product_id: '13', technologist_id: '34', condition: 'All' },
	{ product_id: '14', technologist_id: '2', condition: 'All' },
	{ product_id: '15', technologist_id: '2', condition: 'All' },
	{ product_id: '16', technologist_id: '2', condition: 'All' },
	{ product_id: '17', technologist_id: '2', condition: 'All' },
	{ product_id: '18', technologist_id: '2', condition: 'All' },
	{ product_id: '19', technologist_id: '2', condition: 'All' },
	{ product_id: '20', technologist_id: '2', condition: 'All' },
	{ product_id: '21', technologist_id: '2', condition: 'All' },
	{ product_id: '22', technologist_id: '2', condition: 'All' },
	{ product_id: '23', technologist_id: '2', condition: 'All' },
	{ product_id: '24', technologist_id: '2', condition: 'All' },
	{ product_id: '25', technologist_id: '2', condition: 'All' },
	{ product_id: '26', technologist_id: '2', condition: 'All' },
	{ product_id: '27', technologist_id: '2', condition: 'All' },
	{ product_id: '28', technologist_id: '2', condition: 'All' },
	{ product_id: '29', technologist_id: '2', condition: 'All' },
	{ product_id: '30', technologist_id: '2', condition: 'All' },
	{ product_id: '31', technologist_id: '50', condition: 'All' },
	{ product_id: '32', technologist_id: '2', condition: 'All' },
	{ product_id: '33', technologist_id: '50', condition: 'All' },
	{ product_id: '34', technologist_id: '1', condition: 'All' },
	{ product_id: '35', technologist_id: '1', condition: 'All' },
	{ product_id: '36', technologist_id: '1', condition: 'All' },
	{ product_id: '37', technologist_id: '1', condition: 'All' },
	{ product_id: '38', technologist_id: '1', condition: 'All' },
	{ product_id: '39', technologist_id: '1', condition: 'All' },
	{ product_id: '40', technologist_id: '1', condition: 'All' },
	{ product_id: '41', technologist_id: '1', condition: 'All' },
	{ product_id: '42', technologist_id: '1', condition: 'All' },
	{ product_id: '43', technologist_id: '1', condition: 'All' },
	{ product_id: '44', technologist_id: '1', condition: 'All' },
	{ product_id: '45', technologist_id: '1', condition: 'All' },
	{ product_id: '46', technologist_id: '1', condition: 'All' },
	{ product_id: '47', technologist_id: '1', condition: 'All' },
	{ product_id: '48', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '48', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '49', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '49', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '50', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '50', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '51', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '51', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '52', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '52', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '53', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '53', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '54', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '54', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '55', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '55', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '56', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '56', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '57', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '57', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '58', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '58', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '59', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '59', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '60', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '60', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '61', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '61', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '62', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '62', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '63', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '63', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '64', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '64', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '65', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '65', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '66', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '66', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '67', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '67', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '68', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '68', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '69', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '69', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '70', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '70', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '71', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '71', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '72', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '72', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '73', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '73', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '74', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '74', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '75', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '75', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '76', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '76', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '77', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '77', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '78', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '78', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '79', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '79', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '80', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '80', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '81', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '81', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '82', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '82', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '83', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '83', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '84', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '84', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '85', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '85', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '86', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '86', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '87', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '87', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '88', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '88', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '89', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '89', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '90', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '90', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '91', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '91', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '92', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '92', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '93', technologist_id: '39', condition: 'If utilized in an IP Site Connect system' },
	{ product_id: '93', technologist_id: '38', condition: 'If utilized in a Digital Conventional system' },
	{ product_id: '94', technologist_id: '6', condition: 'All' },
	{ product_id: '95', technologist_id: '6', condition: 'All' },
	{ product_id: '96', technologist_id: '6', condition: 'All' },
	{ product_id: '97', technologist_id: '6', condition: 'All' },
	{ product_id: '98', technologist_id: '6', condition: 'All' },
	{ product_id: '99', technologist_id: '6', condition: 'All' },
	{ product_id: '100', technologist_id: '6', condition: 'All' },
	{ product_id: '101', technologist_id: '6', condition: 'All' },
	{ product_id: '102', technologist_id: '6', condition: 'All' },
	{ product_id: '103', technologist_id: '6', condition: 'All' },
	{ product_id: '104', technologist_id: '6', condition: 'All' },
	{ product_id: '105', technologist_id: '6', condition: 'All' },
	{ product_id: '106', technologist_id: '6', condition: 'All' },
	{ product_id: '107', technologist_id: '6', condition: 'All' },
	{ product_id: '108', technologist_id: '6', condition: 'All' },
	{ product_id: '109', technologist_id: '6', condition: 'All' },
	{ product_id: '110', technologist_id: '6', condition: 'All' },
	{ product_id: '111', technologist_id: '6', condition: 'All' },
	{ product_id: '112', technologist_id: '6', condition: 'All' },
	{ product_id: '113', technologist_id: '6', condition: 'All' },
	{ product_id: '114', technologist_id: '6', condition: 'All' },
	{ product_id: '115', technologist_id: '6', condition: 'All' },
	{ product_id: '116', technologist_id: '41', condition: 'All' },
	{ product_id: '117', technologist_id: '41', condition: 'All' },
	{ product_id: '118', technologist_id: '41', condition: 'All' },
	{ product_id: '119', technologist_id: '41', condition: 'All' },
	{ product_id: '120', technologist_id: '41', condition: 'All' },
	{ product_id: '121', technologist_id: '41', condition: 'All' },
	{ product_id: '122', technologist_id: '41', condition: 'All' },
	{ product_id: '123', technologist_id: '41', condition: 'All' },
	{ product_id: '124', technologist_id: '41', condition: 'All' },
	{ product_id: '125', technologist_id: '41', condition: 'All' },
	{ product_id: '126', technologist_id: '41', condition: 'All' },
	{ product_id: '127', technologist_id: '41', condition: 'All' },
	{ product_id: '128', technologist_id: '41', condition: 'All' },
	{ product_id: '129', technologist_id: '41', condition: 'All' },
	{ product_id: '130', technologist_id: '41', condition: 'All' },
	{ product_id: '131', technologist_id: '41', condition: 'All' },
	{ product_id: '132', technologist_id: '41', condition: 'All' },
	{ product_id: '133', technologist_id: '41', condition: 'All' },
	{ product_id: '134', technologist_id: '41', condition: 'All' },
	{ product_id: '135', technologist_id: '41', condition: 'All' },
	{ product_id: '136', technologist_id: '41', condition: 'All' },
	{ product_id: '137', technologist_id: '41', condition: 'All' },
	{ product_id: '138', technologist_id: '41', condition: 'All' },
	{ product_id: '139', technologist_id: '41', condition: 'All' },
	{ product_id: '140', technologist_id: '41', condition: 'All' },
	{ product_id: '141', technologist_id: '41', condition: 'All' },
	{ product_id: '142', technologist_id: '41', condition: 'All' },
	{ product_id: '143', technologist_id: '1', condition: 'All' },
	{ product_id: '144', technologist_id: '1', condition: 'All' },
	{ product_id: '145', technologist_id: '1', condition: 'All' },
	{ product_id: '146', technologist_id: '1', condition: 'All' },
	{ product_id: '147', technologist_id: '1', condition: 'All' },
	{ product_id: '148', technologist_id: '1', condition: 'All' },
	{ product_id: '149', technologist_id: '1', condition: 'All' },
	{ product_id: '150', technologist_id: '1', condition: 'All' },
	{ product_id: '151', technologist_id: '1', condition: 'All' },
	{ product_id: '152', technologist_id: '1', condition: 'All' },
	{ product_id: '153', technologist_id: '1', condition: 'All' },
	{ product_id: '154', technologist_id: '1', condition: 'All' },
	{ product_id: '155', technologist_id: '1', condition: 'All' },
	{ product_id: '156', technologist_id: '1', condition: 'All' },
	{ product_id: '157', technologist_id: '1', condition: 'All' },
	{ product_id: '158', technologist_id: '1', condition: 'All' },
	{ product_id: '159', technologist_id: '1', condition: 'All' },
	{ product_id: '160', technologist_id: '1', condition: 'All' },
	{ product_id: '161', technologist_id: '1', condition: 'All' },
	{ product_id: '162', technologist_id: '1', condition: 'All' },
	{ product_id: '163', technologist_id: '1', condition: 'All' },
	{ product_id: '164', technologist_id: '52', condition: 'All' },
	{ product_id: '165', technologist_id: '52', condition: 'All' },
	{ product_id: '166', technologist_id: '52', condition: 'All' },
	{ product_id: '167', technologist_id: '52', condition: 'All' },
	{ product_id: '168', technologist_id: '52', condition: 'All' },
	{ product_id: '169', technologist_id: '52', condition: 'All' },
	{ product_id: '170', technologist_id: '52', condition: 'All' },
	{ product_id: '171', technologist_id: '52', condition: 'All' },
	{ product_id: '172', technologist_id: '52', condition: 'All' },
	{ product_id: '173', technologist_id: '52', condition: 'All' },
	{ product_id: '174', technologist_id: '52', condition: 'All' },
	{ product_id: '175', technologist_id: '52', condition: 'All' },
	{ product_id: '176', technologist_id: '52', condition: 'All' },
	{ product_id: '177', technologist_id: '52', condition: 'All' },
	{ product_id: '178', technologist_id: '52', condition: 'All' },
	{ product_id: '179', technologist_id: '52', condition: 'All' },
	{ product_id: '180', technologist_id: '52', condition: 'All' },
	{ product_id: '181', technologist_id: '52', condition: 'All' },
	{ product_id: '182', technologist_id: '52', condition: 'All' },
	{ product_id: '183', technologist_id: '52', condition: 'All' },
	{ product_id: '184', technologist_id: '52', condition: 'All' },
	{ product_id: '185', technologist_id: '52', condition: 'All' },
	{ product_id: '186', technologist_id: '52', condition: 'All' },
	{ product_id: '187', technologist_id: '52', condition: 'All' },
	{ product_id: '188', technologist_id: '52', condition: 'All' },
	{ product_id: '189', technologist_id: '52', condition: 'All' },
	{ product_id: '190', technologist_id: '52', condition: 'All' },
	{ product_id: '191', technologist_id: '52', condition: 'All' },
	{ product_id: '192', technologist_id: '52', condition: 'All' },
	{ product_id: '193', technologist_id: '52', condition: 'All' }
])

ServicerAssignment.create([
	{ product_id: '1', servicer_id: '1', condition: 'All' },
	{ product_id: '2', servicer_id: '1', condition: 'All' },
	{ product_id: '3', servicer_id: '2', condition: 'All' },
	{ product_id: '4', servicer_id: '1', condition: 'All' },
	{ product_id: '5', servicer_id: '1', condition: 'All' },
	{ product_id: '6', servicer_id: '1', condition: 'All' },
	{ product_id: '7', servicer_id: '1', condition: 'All' },
	{ product_id: '8', servicer_id: '1', condition: 'All' },
	{ product_id: '9', servicer_id: '3', condition: 'All' },
	{ product_id: '10', servicer_id: '2', condition: 'All' },
	{ product_id: '11', servicer_id: '1', condition: 'All' },
	{ product_id: '12', servicer_id: '2', condition: 'All' },
	{ product_id: '13', servicer_id: '2', condition: 'All' },
	{ product_id: '14', servicer_id: '2', condition: 'All' },
	{ product_id: '15', servicer_id: '2', condition: 'All' },
	{ product_id: '16', servicer_id: '2', condition: 'All' },
	{ product_id: '17', servicer_id: '2', condition: 'All' },
	{ product_id: '18', servicer_id: '2', condition: 'All' },
	{ product_id: '19', servicer_id: '2', condition: 'All' },
	{ product_id: '20', servicer_id: '2', condition: 'All' },
	{ product_id: '21', servicer_id: '2', condition: 'All' },
	{ product_id: '22', servicer_id: '2', condition: 'All' },
	{ product_id: '23', servicer_id: '2', condition: 'All' },
	{ product_id: '24', servicer_id: '1', condition: 'All' },
	{ product_id: '25', servicer_id: '2', condition: 'All' },
	{ product_id: '26', servicer_id: '2', condition: 'All' },
	{ product_id: '27', servicer_id: '2', condition: 'All' },
	{ product_id: '28', servicer_id: '2', condition: 'All' },
	{ product_id: '29', servicer_id: '2', condition: 'All' },
	{ product_id: '30', servicer_id: '2', condition: 'All' },
	{ product_id: '31', servicer_id: '10', condition: 'All' },
	{ product_id: '32', servicer_id: '2', condition: 'All' },
	{ product_id: '33', servicer_id: '10', condition: 'All' },
	{ product_id: '34', servicer_id: '1', condition: 'All' },
	{ product_id: '35', servicer_id: '1', condition: 'All' },
	{ product_id: '36', servicer_id: '1', condition: 'All' },
	{ product_id: '37', servicer_id: '1', condition: 'All' },
	{ product_id: '38', servicer_id: '1', condition: 'All' },
	{ product_id: '39', servicer_id: '1', condition: 'All' },
	{ product_id: '40', servicer_id: '1', condition: 'All' },
	{ product_id: '41', servicer_id: '1', condition: 'All' },
	{ product_id: '42', servicer_id: '1', condition: 'All' },
	{ product_id: '43', servicer_id: '1', condition: 'All' },
	{ product_id: '44', servicer_id: '1', condition: 'All' },
	{ product_id: '45', servicer_id: '1', condition: 'All' },
	{ product_id: '46', servicer_id: '1', condition: 'All' },
	{ product_id: '47', servicer_id: '1', condition: 'All' },
	{ product_id: '48', servicer_id: '2', condition: 'All' },
	{ product_id: '49', servicer_id: '2', condition: 'All' },
	{ product_id: '50', servicer_id: '2', condition: 'All' },
	{ product_id: '51', servicer_id: '2', condition: 'All' },
	{ product_id: '52', servicer_id: '2', condition: 'All' },
	{ product_id: '53', servicer_id: '2', condition: 'All' },
	{ product_id: '54', servicer_id: '2', condition: 'All' },
	{ product_id: '55', servicer_id: '2', condition: 'All' },
	{ product_id: '56', servicer_id: '2', condition: 'All' },
	{ product_id: '57', servicer_id: '2', condition: 'All' },
	{ product_id: '58', servicer_id: '2', condition: 'All' },
	{ product_id: '59', servicer_id: '2', condition: 'All' },
	{ product_id: '60', servicer_id: '2', condition: 'All' },
	{ product_id: '61', servicer_id: '2', condition: 'All' },
	{ product_id: '62', servicer_id: '2', condition: 'All' },
	{ product_id: '63', servicer_id: '2', condition: 'All' },
	{ product_id: '64', servicer_id: '2', condition: 'All' },
	{ product_id: '65', servicer_id: '2', condition: 'All' },
	{ product_id: '66', servicer_id: '2', condition: 'All' },
	{ product_id: '67', servicer_id: '2', condition: 'All' },
	{ product_id: '68', servicer_id: '2', condition: 'All' },
	{ product_id: '69', servicer_id: '2', condition: 'All' },
	{ product_id: '70', servicer_id: '2', condition: 'All' },
	{ product_id: '71', servicer_id: '2', condition: 'All' },
	{ product_id: '72', servicer_id: '2', condition: 'All' },
	{ product_id: '73', servicer_id: '2', condition: 'All' },
	{ product_id: '74', servicer_id: '2', condition: 'All' },
	{ product_id: '75', servicer_id: '2', condition: 'All' },
	{ product_id: '76', servicer_id: '2', condition: 'All' },
	{ product_id: '77', servicer_id: '2', condition: 'All' },
	{ product_id: '78', servicer_id: '2', condition: 'All' },
	{ product_id: '79', servicer_id: '2', condition: 'All' },
	{ product_id: '80', servicer_id: '2', condition: 'All' },
	{ product_id: '81', servicer_id: '2', condition: 'All' },
	{ product_id: '82', servicer_id: '2', condition: 'All' },
	{ product_id: '83', servicer_id: '2', condition: 'All' },
	{ product_id: '84', servicer_id: '2', condition: 'All' },
	{ product_id: '85', servicer_id: '2', condition: 'All' },
	{ product_id: '86', servicer_id: '2', condition: 'All' },
	{ product_id: '87', servicer_id: '2', condition: 'All' },
	{ product_id: '88', servicer_id: '2', condition: 'All' },
	{ product_id: '89', servicer_id: '2', condition: 'All' },
	{ product_id: '90', servicer_id: '2', condition: 'All' },
	{ product_id: '91', servicer_id: '2', condition: 'All' },
	{ product_id: '92', servicer_id: '2', condition: 'All' },
	{ product_id: '93', servicer_id: '2', condition: 'All' },
	{ product_id: '94', servicer_id: '7', condition: 'All' },
	{ product_id: '95', servicer_id: '7', condition: 'All' },
	{ product_id: '96', servicer_id: '7', condition: 'All' },
	{ product_id: '97', servicer_id: '7', condition: 'All' },
	{ product_id: '98', servicer_id: '7', condition: 'All' },
	{ product_id: '99', servicer_id: '7', condition: 'All' },
	{ product_id: '100', servicer_id: '7', condition: 'All' },
	{ product_id: '101', servicer_id: '7', condition: 'All' },
	{ product_id: '102', servicer_id: '7', condition: 'All' },
	{ product_id: '103', servicer_id: '7', condition: 'All' },
	{ product_id: '104', servicer_id: '7', condition: 'All' },
	{ product_id: '105', servicer_id: '7', condition: 'All' },
	{ product_id: '106', servicer_id: '7', condition: 'All' },
	{ product_id: '107', servicer_id: '7', condition: 'All' },
	{ product_id: '108', servicer_id: '7', condition: 'All' },
	{ product_id: '109', servicer_id: '7', condition: 'All' },
	{ product_id: '110', servicer_id: '7', condition: 'All' },
	{ product_id: '111', servicer_id: '7', condition: 'All' },
	{ product_id: '112', servicer_id: '7', condition: 'All' },
	{ product_id: '113', servicer_id: '7', condition: 'All' },
	{ product_id: '114', servicer_id: '7', condition: 'All' },
	{ product_id: '115', servicer_id: '7', condition: 'All' },
	{ product_id: '116', servicer_id: '2', condition: 'All' },
	{ product_id: '117', servicer_id: '2', condition: 'All' },
	{ product_id: '118', servicer_id: '2', condition: 'All' },
	{ product_id: '119', servicer_id: '2', condition: 'All' },
	{ product_id: '120', servicer_id: '2', condition: 'All' },
	{ product_id: '121', servicer_id: '2', condition: 'All' },
	{ product_id: '122', servicer_id: '2', condition: 'All' },
	{ product_id: '123', servicer_id: '2', condition: 'All' },
	{ product_id: '124', servicer_id: '2', condition: 'All' },
	{ product_id: '125', servicer_id: '2', condition: 'All' },
	{ product_id: '126', servicer_id: '2', condition: 'All' },
	{ product_id: '127', servicer_id: '2', condition: 'All' },
	{ product_id: '128', servicer_id: '2', condition: 'All' },
	{ product_id: '129', servicer_id: '2', condition: 'All' },
	{ product_id: '130', servicer_id: '2', condition: 'All' },
	{ product_id: '131', servicer_id: '2', condition: 'All' },
	{ product_id: '132', servicer_id: '2', condition: 'All' },
	{ product_id: '133', servicer_id: '2', condition: 'All' },
	{ product_id: '134', servicer_id: '2', condition: 'All' },
	{ product_id: '135', servicer_id: '2', condition: 'All' },
	{ product_id: '136', servicer_id: '2', condition: 'All' },
	{ product_id: '137', servicer_id: '2', condition: 'All' },
	{ product_id: '138', servicer_id: '2', condition: 'All' },
	{ product_id: '139', servicer_id: '2', condition: 'All' },
	{ product_id: '140', servicer_id: '2', condition: 'All' },
	{ product_id: '141', servicer_id: '2', condition: 'All' },
	{ product_id: '142', servicer_id: '2', condition: 'All' },
	{ product_id: '143', servicer_id: '1', condition: 'All' },
	{ product_id: '144', servicer_id: '1', condition: 'All' },
	{ product_id: '145', servicer_id: '1', condition: 'All' },
	{ product_id: '146', servicer_id: '1', condition: 'All' },
	{ product_id: '147', servicer_id: '1', condition: 'All' },
	{ product_id: '148', servicer_id: '1', condition: 'All' },
	{ product_id: '149', servicer_id: '1', condition: 'All' },
	{ product_id: '150', servicer_id: '1', condition: 'All' },
	{ product_id: '151', servicer_id: '1', condition: 'All' },
	{ product_id: '152', servicer_id: '1', condition: 'All' },
	{ product_id: '153', servicer_id: '1', condition: 'All' },
	{ product_id: '154', servicer_id: '1', condition: 'All' },
	{ product_id: '155', servicer_id: '1', condition: 'All' },
	{ product_id: '156', servicer_id: '1', condition: 'All' },
	{ product_id: '157', servicer_id: '1', condition: 'All' },
	{ product_id: '158', servicer_id: '1', condition: 'All' },
	{ product_id: '159', servicer_id: '1', condition: 'All' },
	{ product_id: '160', servicer_id: '1', condition: 'All' },
	{ product_id: '161', servicer_id: '1', condition: 'All' },
	{ product_id: '162', servicer_id: '1', condition: 'All' },
	{ product_id: '163', servicer_id: '1', condition: 'All' },
	{ product_id: '164', servicer_id: '30', condition: 'All' },
	{ product_id: '165', servicer_id: '30', condition: 'All' },
	{ product_id: '166', servicer_id: '30', condition: 'All' },
	{ product_id: '167', servicer_id: '30', condition: 'All' },
	{ product_id: '168', servicer_id: '30', condition: 'All' },
	{ product_id: '169', servicer_id: '30', condition: 'All' },
	{ product_id: '170', servicer_id: '30', condition: 'All' },
	{ product_id: '171', servicer_id: '30', condition: 'All' },
	{ product_id: '172', servicer_id: '30', condition: 'All' },
	{ product_id: '173', servicer_id: '30', condition: 'All' },
	{ product_id: '174', servicer_id: '30', condition: 'All' },
	{ product_id: '175', servicer_id: '30', condition: 'All' },
	{ product_id: '176', servicer_id: '30', condition: 'All' },
	{ product_id: '177', servicer_id: '30', condition: 'All' },
	{ product_id: '178', servicer_id: '30', condition: 'All' },
	{ product_id: '179', servicer_id: '30', condition: 'All' },
	{ product_id: '180', servicer_id: '30', condition: 'All' },
	{ product_id: '181', servicer_id: '30', condition: 'All' },
	{ product_id: '182', servicer_id: '30', condition: 'All' },
	{ product_id: '183', servicer_id: '30', condition: 'All' },
	{ product_id: '184', servicer_id: '30', condition: 'All' },
	{ product_id: '185', servicer_id: '30', condition: 'All' },
	{ product_id: '186', servicer_id: '30', condition: 'All' },
	{ product_id: '187', servicer_id: '30', condition: 'All' },
	{ product_id: '188', servicer_id: '30', condition: 'All' },
	{ product_id: '189', servicer_id: '30', condition: 'All' },
	{ product_id: '190', servicer_id: '30', condition: 'All' },
	{ product_id: '191', servicer_id: '30', condition: 'All' },
	{ product_id: '192', servicer_id: '30', condition: 'All' },
	{ product_id: '193', servicer_id: '30', condition: 'All' }
])